package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'AShelve'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("AShelve")) {
    check(name == "perforce swarm commit statuses") {
        "Unexpected name: '$name'"
    }
    name = "perforce swarm commit statuses main"
}
